# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata_box',
            name='last_online',
            field=models.DateTimeField(blank=True),
        ),
    ]
