# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_auto_20160403_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata_box',
            name='fw_version',
            field=models.CharField(blank=True, max_length=23),
        ),
        migrations.AlterField(
            model_name='ata_box',
            name='mac',
            field=models.CharField(blank=True, max_length=23),
        ),
        migrations.AlterField(
            model_name='ata_box',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='ata_box',
            name='status',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
