# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0003_auto_20160403_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata_box',
            name='mac',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
