# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_auto_20160403_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata_box',
            name='last_online',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
