# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_auto_20160403_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata_box',
            name='sip_control',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ata_box',
            name='sip_voice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ata_box',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
