# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0007_auto_20160404_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata_box',
            name='api_cell_signal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ata_box',
            name='api_internet',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ata_box',
            name='api_sip_control_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ata_box',
            name='api_sip_voice_registered',
            field=models.BooleanField(default=False),
        ),
    ]
