# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0008_auto_20160528_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata_box',
            name='customer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
