# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0011_auto_20160529_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tftp_dir', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=12)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('sip_server', models.CharField(max_length=20)),
                ('sip_user', models.CharField(max_length=12)),
                ('sip_password', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('end_customer_no', models.CharField(max_length=12)),
                ('end_customer_fname', models.CharField(max_length=20)),
                ('end_customer_lname', models.CharField(max_length=20)),
                ('end_customer_address', models.CharField(max_length=40)),
                ('end_customer_zip', models.CharField(max_length=12)),
                ('end_customer_city', models.CharField(max_length=12)),
                ('sip_msg_server', models.CharField(max_length=12)),
                ('sip_msg_user', models.CharField(max_length=12)),
                ('sip_msg_password', models.CharField(max_length=12)),
                ('inet_connection_type', models.CharField(max_length=12)),
                ('signal_strenght', models.CharField(max_length=12)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.company')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.company')),
            ],
        ),
        migrations.DeleteModel(
            name='ATA_box',
        ),
    ]
