# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0013_auto_20160602_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='companyid',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='myuser',
        ),
    ]
