# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site1', '0014_auto_20160602_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='companyid',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
