# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0015_auto_20160602_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
