# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0016_auto_20160602_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='end_customer_address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='end_customer_city',
            new_name='customer_city',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='end_customer_fname',
            new_name='customer_fname',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='end_customer_lname',
            new_name='customer_lname',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='end_customer_no',
            new_name='customer_no',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='end_customer_zip',
            new_name='customer_zip',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='inet_connection_type',
            new_name='inet_type',
        ),
    ]
