# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0018_auto_20160604_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='companyid',
            new_name='company',
        ),
    ]
