# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0020_auto_20160604_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='devices',
            new_name='device',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('read_devices', 'Read devices'),)},
        ),
    ]
