# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0021_auto_20160604_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inet_type',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='signal_strenght',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
