# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0022_auto_20160604_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AlterField(
            model_name='device',
            name='customer_fname',
            field=models.CharField(max_length=20, verbose_name='Customer Firts name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer_lname',
            field=models.CharField(max_length=20, verbose_name='Customer Second name'),
        ),
    ]
