# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0025_auto_20160606_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='customer_fname',
            field=models.CharField(max_length=20, verbose_name='Customer First name'),
        ),
    ]
