# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0026_auto_20160606_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sip_control_registered',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Registered on managment server'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sip_voip_registered',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Registered on VoIP server'),
        ),
    ]
