# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0027_auto_20160606_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
