# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0028_device_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sip_msg_server',
            field=models.CharField(default='ata.sipstar.ch', max_length=12),
        ),
        migrations.AlterField(
            model_name='device',
            name='sip_server',
            field=models.CharField(default='sip.phone.suissephone.ch', max_length=20),
        ),
    ]
