# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0033_auto_20160608_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='customer_fname',
            field=models.CharField(max_length=30, verbose_name='Customer First name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer_lname',
            field=models.CharField(max_length=30, verbose_name='Customer Second name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer_zip',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='sip_msg_password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='sip_msg_user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='sip_password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='sip_user',
            field=models.CharField(max_length=30),
        ),
    ]
