# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0034_auto_20160614_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='voip1_rule1_length',
            field=models.CharField(blank=True, default="'1'", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule1_offset',
            field=models.CharField(blank=True, default="'1'", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule1_pattern',
            field=models.CharField(blank=True, default='_9.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule1_prefix',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule1_suffix',
            field=models.CharField(blank=True, default="'1'", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule2_length',
            field=models.CharField(blank=True, default="'1'", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule2_offset',
            field=models.CharField(blank=True, default="'1'", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule2_pattern',
            field=models.CharField(blank=True, default='_8.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule2_prefix',
            field=models.CharField(blank=True, default='1', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule2_suffix',
            field=models.CharField(blank=True, default="'1'", max_length=12, null=True),
        ),
    ]
