# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0035_auto_20160614_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='voip1_rule2_length',
        ),
        migrations.RemoveField(
            model_name='device',
            name='voip1_rule2_offset',
        ),
        migrations.RemoveField(
            model_name='device',
            name='voip1_rule2_pattern',
        ),
        migrations.RemoveField(
            model_name='device',
            name='voip1_rule2_prefix',
        ),
        migrations.RemoveField(
            model_name='device',
            name='voip1_rule2_suffix',
        ),
        migrations.AddField(
            model_name='device',
            name='voip1_rule1_callerid',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
