# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0037_auto_20160615_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='voip1_rule1_pattern',
        ),
    ]
