# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0038_remove_device_voip1_rule1_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sip_msg_password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
