# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0039_auto_20160630_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sip_msg_password',
            field=models.CharField(blank=True, default='**autogeneration**', max_length=30, null=True),
        ),
    ]
