# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0040_auto_20160630_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sip_msg_user',
            field=models.CharField(default='**autogeneration**', max_length=30),
        ),
    ]
