# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0041_auto_20160630_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='voip1_rule1_length',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
